export const GET_ALL_STOCKS = 'GET_ALL_STOCKS';
export const GET_NEXT_STOCKS = 'GET_NEXT_STOCKS';
export const ADD_NEW_STOCK = 'ADD_NEW_STOCK';
export const GET_STOCK_DETAIL = 'GET_STOCK_DETAIL';
export const EDIT_STOCK = 'EDIT_STOCK';

export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
export const GET_NEXT_SUPPLIERS = 'GET_NEXT_SUPPLIERS';
export const ADD_NEW_SUPPLIER = 'ADD_NEW_SUPPLIER';
export const GET_SUPPLIER_DETAIL = 'GET_SUPPLIER_DETAIL';
export const EDIT_SUPPLIER = 'EDIT_SUPPLIER';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_SUBCATEGORIES = 'GET_SUBCATEGORIES';

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_NEXT_PRODUCTS = 'GET_NEXT_PRODUCTS';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';