export const GET_ALL_STOCKS = 'GET_ALL_STOCKS';
export const GET_NEXT_STOCKS = 'GET_NEXT_STOCKS';
export const ADD_NEW_STOCK = 'ADD_NEW_STOCK';
export const GET_STOCK_DETAIL = 'GET_STOCK_DETAIL';
export const EDIT_STOCK = 'EDIT_STOCK';

export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
export const GET_NEXT_SUPPLIERS = 'GET_NEXT_SUPPLIERS';
export const ADD_NEW_SUPPLIER = 'ADD_NEW_SUPPLIER';
export const GET_SUPPLIER_DETAIL = 'GET_SUPPLIER_DETAIL';